/* Auto-generated by genmsg_cpp for file /home/odroid/catkin_ws/src/roscopter/msg/Control.msg */
#ifndef ROSCOPTER_MESSAGE_CONTROL_H
#define ROSCOPTER_MESSAGE_CONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace roscopter
{
template <class ContainerAllocator>
struct Control_ {
  typedef Control_<ContainerAllocator> Type;

  Control_()
  : roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , thrust(0.0)
  {
  }

  Control_(const ContainerAllocator& _alloc)
  : roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , thrust(0.0)
  {
  }

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;

  typedef float _thrust_type;
  float thrust;


  typedef boost::shared_ptr< ::roscopter::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter::Control_<ContainerAllocator>  const> ConstPtr;
}; // struct Control
typedef  ::roscopter::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::roscopter::Control> ControlPtr;
typedef boost::shared_ptr< ::roscopter::Control const> ControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::roscopter::Control_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::roscopter::Control_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace roscopter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::roscopter::Control_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::roscopter::Control_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::roscopter::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f2b64ccef8f731e7d5b721d65f7d91ec";
  }

  static const char* value(const  ::roscopter::Control_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf2b64ccef8f731e7ULL;
  static const uint64_t static_value2 = 0xd5b721d65f7d91ecULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "roscopter/Control";
  }

  static const char* value(const  ::roscopter::Control_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::roscopter::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#arducopter control commands\n\
\n\
\n\
float32 roll   #desired roll angle in radians\n\
float32 pitch  #desired roll angle in radians\n\
float32 yaw    #desired roll angle in radians\n\
float32 thrust #collective thrust, normalized to 0..1\n\
\n\
";
  }

  static const char* value(const  ::roscopter::Control_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::roscopter::Control_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::roscopter::Control_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.thrust);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Control_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::roscopter::Control_<ContainerAllocator> & v) 
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "thrust: ";
    Printer<float>::stream(s, indent + "  ", v.thrust);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MESSAGE_CONTROL_H

