"""autogenerated by genpy from mms/Arm.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Arm(genpy.Message):
  _md5sum = "694dce2fa7eb0edc65e00dea01480dec"
  _type = "mms/Arm"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# false = disarm; true = arm
bool arm_disarm
# false = old message; true = new message available
bool new_arm_disarm

"""
  __slots__ = ['arm_disarm','new_arm_disarm']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       arm_disarm,new_arm_disarm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Arm, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.arm_disarm is None:
        self.arm_disarm = False
      if self.new_arm_disarm is None:
        self.new_arm_disarm = False
    else:
      self.arm_disarm = False
      self.new_arm_disarm = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.arm_disarm, _x.new_arm_disarm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.arm_disarm, _x.new_arm_disarm,) = _struct_2B.unpack(str[start:end])
      self.arm_disarm = bool(self.arm_disarm)
      self.new_arm_disarm = bool(self.new_arm_disarm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.arm_disarm, _x.new_arm_disarm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.arm_disarm, _x.new_arm_disarm,) = _struct_2B.unpack(str[start:end])
      self.arm_disarm = bool(self.arm_disarm)
      self.new_arm_disarm = bool(self.new_arm_disarm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
