obstacle_range: 30.0
raytrace_range: 30.0
footprint: [[0.8, 0.8], [0.8, -0.8], [-0.8, -0.8], [-0.8, 0.8]]
inflation_radius: 1.15
observation_sources: laser
laser: {sensor_frame: laser, data_type: LaserScan, topic: /first, marking: true, clearing: true}
min_obstacle_height: 0.0
#min_obstacle_height: 2.0

