global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 2.5
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 50
  height: 50
  resolution: 0.05
  origin_x: -25
  origin_y: -25

