global_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 2.5
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 20
  height: 20
  resolution: 0.1
  origin_x: -10
  origin_y: -10

