local_costmap:
  global_frame: map
  robot_base_frame: base
  update_frequency: 1.0 #5.0 #50
  publish_frequency: 0.5 #1.0
  static_map: false
  rolling_window: true
  width: 0.5 #4.0
  height: 0.5 #4.0
  resolution: 0.05
