# Common configuration for guidance_node

#TODO check syntax

#debug param
debug/testOffset: 1.0

#control param
param/sat_xy: 1.5
param/sat_z: 1.5
param/sat_yaw: 3.14
param/gain_NE: 0.3
param/gain_D: 0.27
param/gain_yaw: 0.11
param/deadzone_NE: 0.0
param/deadzone_D: 0.0
param/gain_integralDown: 0.0

#reference
# at ingegneria
ref/latitude_ref: 444884934
ref/longitude_ref: 113291952
ref/altitude_ref: 3000
ref/yaw_ref: 0

#frequency
frequency: 10
