/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/odroid/catkin_ws/src/mavros/mavros/srv/CommandLong.srv
 *
 */


#ifndef MAVROS_MESSAGE_COMMANDLONG_H
#define MAVROS_MESSAGE_COMMANDLONG_H

#include <ros/service_traits.h>


#include <mavros/CommandLongRequest.h>
#include <mavros/CommandLongResponse.h>


namespace mavros
{

struct CommandLong
{

typedef CommandLongRequest Request;
typedef CommandLongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandLong
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::CommandLong > {
  static const char* value()
  {
    return "f6050a9a4b3570f1f26029366646d348";
  }

  static const char* value(const ::mavros::CommandLong&) { return value(); }
};

template<>
struct DataType< ::mavros::CommandLong > {
  static const char* value()
  {
    return "mavros/CommandLong";
  }

  static const char* value(const ::mavros::CommandLong&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::CommandLongRequest> should match 
// service_traits::MD5Sum< ::mavros::CommandLong > 
template<>
struct MD5Sum< ::mavros::CommandLongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandLongRequest> should match 
// service_traits::DataType< ::mavros::CommandLong > 
template<>
struct DataType< ::mavros::CommandLongRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::CommandLongResponse> should match 
// service_traits::MD5Sum< ::mavros::CommandLong > 
template<>
struct MD5Sum< ::mavros::CommandLongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::CommandLongResponse> should match 
// service_traits::DataType< ::mavros::CommandLong > 
template<>
struct DataType< ::mavros::CommandLongResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::CommandLong >::value();
  }
  static const char* value(const ::mavros::CommandLongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_COMMANDLONG_H
