/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/odroid/catkin_ws/src/mavros/mavros/srv/StreamRate.srv
 *
 */


#ifndef MAVROS_MESSAGE_STREAMRATE_H
#define MAVROS_MESSAGE_STREAMRATE_H

#include <ros/service_traits.h>


#include <mavros/StreamRateRequest.h>
#include <mavros/StreamRateResponse.h>


namespace mavros
{

struct StreamRate
{

typedef StreamRateRequest Request;
typedef StreamRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StreamRate
} // namespace mavros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros::StreamRate > {
  static const char* value()
  {
    return "d12f7661724c8ba25f67ba597bb7d039";
  }

  static const char* value(const ::mavros::StreamRate&) { return value(); }
};

template<>
struct DataType< ::mavros::StreamRate > {
  static const char* value()
  {
    return "mavros/StreamRate";
  }

  static const char* value(const ::mavros::StreamRate&) { return value(); }
};


// service_traits::MD5Sum< ::mavros::StreamRateRequest> should match 
// service_traits::MD5Sum< ::mavros::StreamRate > 
template<>
struct MD5Sum< ::mavros::StreamRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::StreamRate >::value();
  }
  static const char* value(const ::mavros::StreamRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::StreamRateRequest> should match 
// service_traits::DataType< ::mavros::StreamRate > 
template<>
struct DataType< ::mavros::StreamRateRequest>
{
  static const char* value()
  {
    return DataType< ::mavros::StreamRate >::value();
  }
  static const char* value(const ::mavros::StreamRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros::StreamRateResponse> should match 
// service_traits::MD5Sum< ::mavros::StreamRate > 
template<>
struct MD5Sum< ::mavros::StreamRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros::StreamRate >::value();
  }
  static const char* value(const ::mavros::StreamRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros::StreamRateResponse> should match 
// service_traits::DataType< ::mavros::StreamRate > 
template<>
struct DataType< ::mavros::StreamRateResponse>
{
  static const char* value()
  {
    return DataType< ::mavros::StreamRate >::value();
  }
  static const char* value(const ::mavros::StreamRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MESSAGE_STREAMRATE_H
