/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/mms/msg/Ack_cmd.msg
 *
 */


#ifndef MMS_MESSAGE_ACK_CMD_H
#define MMS_MESSAGE_ACK_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mms
{
template <class ContainerAllocator>
struct Ack_cmd_
{
  typedef Ack_cmd_<ContainerAllocator> Type;

  Ack_cmd_()
    : mission_item_reached(false)
    , mav_mission_accepted(false)  {
    }
  Ack_cmd_(const ContainerAllocator& _alloc)
    : mission_item_reached(false)
    , mav_mission_accepted(false)  {
    }



   typedef uint8_t _mission_item_reached_type;
  _mission_item_reached_type mission_item_reached;

   typedef uint8_t _mav_mission_accepted_type;
  _mav_mission_accepted_type mav_mission_accepted;




  typedef boost::shared_ptr< ::mms::Ack_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mms::Ack_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Ack_cmd_

typedef ::mms::Ack_cmd_<std::allocator<void> > Ack_cmd;

typedef boost::shared_ptr< ::mms::Ack_cmd > Ack_cmdPtr;
typedef boost::shared_ptr< ::mms::Ack_cmd const> Ack_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mms::Ack_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mms::Ack_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mms': ['/home/odroid/catkin_ws/src/mms/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mms::Ack_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mms::Ack_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mms::Ack_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mms::Ack_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mms::Ack_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mms::Ack_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mms::Ack_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39d26c985985072c3c449a1c32116e79";
  }

  static const char* value(const ::mms::Ack_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39d26c985985072cULL;
  static const uint64_t static_value2 = 0x3c449a1c32116e79ULL;
};

template<class ContainerAllocator>
struct DataType< ::mms::Ack_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mms/Ack_cmd";
  }

  static const char* value(const ::mms::Ack_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mms::Ack_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# false = mission item not reached, true = mission item reached\n\
bool mission_item_reached\n\
# false = mission item not accepted, true = mission item accepted\n\
bool mav_mission_accepted\n\
";
  }

  static const char* value(const ::mms::Ack_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mms::Ack_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_item_reached);
      stream.next(m.mav_mission_accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Ack_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mms::Ack_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mms::Ack_cmd_<ContainerAllocator>& v)
  {
    s << indent << "mission_item_reached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mission_item_reached);
    s << indent << "mav_mission_accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mav_mission_accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MMS_MESSAGE_ACK_CMD_H
