/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/mms/msg/Arm.msg
 *
 */


#ifndef MMS_MESSAGE_ARM_H
#define MMS_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mms
{
template <class ContainerAllocator>
struct Arm_
{
  typedef Arm_<ContainerAllocator> Type;

  Arm_()
    : arm_disarm(false)
    , new_arm_disarm(false)  {
    }
  Arm_(const ContainerAllocator& _alloc)
    : arm_disarm(false)
    , new_arm_disarm(false)  {
    }



   typedef uint8_t _arm_disarm_type;
  _arm_disarm_type arm_disarm;

   typedef uint8_t _new_arm_disarm_type;
  _new_arm_disarm_type new_arm_disarm;




  typedef boost::shared_ptr< ::mms::Arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mms::Arm_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_

typedef ::mms::Arm_<std::allocator<void> > Arm;

typedef boost::shared_ptr< ::mms::Arm > ArmPtr;
typedef boost::shared_ptr< ::mms::Arm const> ArmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mms::Arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mms::Arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mms': ['/home/odroid/catkin_ws/src/mms/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mms::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mms::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mms::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mms::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mms::Arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mms::Arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mms::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "694dce2fa7eb0edc65e00dea01480dec";
  }

  static const char* value(const ::mms::Arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x694dce2fa7eb0edcULL;
  static const uint64_t static_value2 = 0x65e00dea01480decULL;
};

template<class ContainerAllocator>
struct DataType< ::mms::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mms/Arm";
  }

  static const char* value(const ::mms::Arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mms::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# false = disarm; true = arm\n\
bool arm_disarm\n\
# false = old message; true = new message available\n\
bool new_arm_disarm\n\
";
  }

  static const char* value(const ::mms::Arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mms::Arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm_disarm);
      stream.next(m.new_arm_disarm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mms::Arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mms::Arm_<ContainerAllocator>& v)
  {
    s << indent << "arm_disarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm_disarm);
    s << indent << "new_arm_disarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.new_arm_disarm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MMS_MESSAGE_ARM_H
