# thanks to jsk-ros-pkg
# vim:set ts=2 sw=2 et:
language: cpp
compiler:
  - gcc
  #- clang
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "ieyA/jKHN1rVAQ8qFvXx6wdcUozFR5QBxUpQuEcItl4yv0bPnRp0xO9X/BhNFt6V85L8jEw9XNz4uHTUeAtghZZxpKCQ8de1NP49d7boyCTLQx/WsJ/bSPubAZOcnvbi9SoOTyymM94jdA1k46ndznI1ZZ713uSrPdIcg6o8Q9A="
    - ROS_DISTRO=hydro # wait until travis will update to 14.04
  matrix:
    - MAVLINK_DIALECT=common
    - MAVLINK_DIALECT=pixhawk

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
    #- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros python-rosinstall
    # Setup rosdep
  - sudo rosdep init
  - rosdep update

install:
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - wstool init .
  - ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  - cd ../
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y

before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - rospack profile
script:
  - cd ~/ros/ws_$REPOSITORY_NAME
  - catkin_make -j4 -DMAVLINK_DIALECT=$MAVLINK_DIALECT
  - catkin_make install
  - rm -fr devel src build; source install/setup.bash

after_failure:
  - if [ -e ./build/Testing/Temporary/LastTest.log ]; then cat ./build/Testing/Temporary/LastTest.log; fi
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done

addons:
  coverity_scan:
    project:
      name: "mavlink/mavros"
      description: "Build submitted via Travis CI"
    notification_email: vooon341@gmail.com
    build_command_prepend: cd ~/ros/ws_$REPOSITORY_NAME/src/mavros &&
      ln -s /opt/ros/$ROS_DISTRO/share/catkin/cmake/toplevel.cmake CMakeLists.txt &&
      cmake .
    build_command: make -j4
    branch_pattern: coverity_scan

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b856f174ff9736ad23ec
    on_success: change
    on_failure: always
    on_start: false
