#rec1_modulus                   : Signal strength (?) (int)     
#rec1_direction                 : Signal direction (rad) (int) 
#rec2_modulus                   : Signal strength (?) (int)     
#rec2_direction                 : Signal direction (rad) (int) 
#rec3_modulus                   : Signal strength (?) (int)     
#rec3_direction                 : Signal direction (rad) (int) 
#rec4_modulus                   : Signal strength (?) (int)     
#rec4_direction                 : Signal direction (rad) (int) 

Header header
int32 rec1_modulus
int32 rec1_direction
int32 rec2_modulus
int32 rec2_direction
int32 rec3_modulus
int32 rec3_direction
int32 rec4_modulus
int32 rec4_direction
