/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/camera_handler_SHERPA/msg/Camera.msg
 *
 */


#ifndef CAMERA_HANDLER_SHERPA_MESSAGE_CAMERA_H
#define CAMERA_HANDLER_SHERPA_MESSAGE_CAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_handler_SHERPA
{
template <class ContainerAllocator>
struct Camera_
{
  typedef Camera_<ContainerAllocator> Type;

  Camera_()
    : take_pic(false)
    , take_vid(false)  {
    }
  Camera_(const ContainerAllocator& _alloc)
    : take_pic(false)
    , take_vid(false)  {
    }



   typedef uint8_t _take_pic_type;
  _take_pic_type take_pic;

   typedef uint8_t _take_vid_type;
  _take_vid_type take_vid;




  typedef boost::shared_ptr< ::camera_handler_SHERPA::Camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_handler_SHERPA::Camera_<ContainerAllocator> const> ConstPtr;

}; // struct Camera_

typedef ::camera_handler_SHERPA::Camera_<std::allocator<void> > Camera;

typedef boost::shared_ptr< ::camera_handler_SHERPA::Camera > CameraPtr;
typedef boost::shared_ptr< ::camera_handler_SHERPA::Camera const> CameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_handler_SHERPA::Camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_handler_SHERPA

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'camera_handler_SHERPA': ['/home/odroid/catkin_ws/src/camera_handler_SHERPA/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_handler_SHERPA::Camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_handler_SHERPA::Camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_handler_SHERPA::Camera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef44d9a6b4c587ef4ea335ff23618ea6";
  }

  static const char* value(const ::camera_handler_SHERPA::Camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef44d9a6b4c587efULL;
  static const uint64_t static_value2 = 0x4ea335ff23618ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_handler_SHERPA/Camera";
  }

  static const char* value(const ::camera_handler_SHERPA::Camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# true when requested a picture and false after the picture is taken\n\
bool take_pic\n\
# true when starting a video and false when video is stopped\n\
bool take_vid\n\
";
  }

  static const char* value(const ::camera_handler_SHERPA::Camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.take_pic);
      stream.next(m.take_vid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_handler_SHERPA::Camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_handler_SHERPA::Camera_<ContainerAllocator>& v)
  {
    s << indent << "take_pic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.take_pic);
    s << indent << "take_vid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.take_vid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_HANDLER_SHERPA_MESSAGE_CAMERA_H
