/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/px-ros-pkg/px_comm/srv/SetCameraInfo.srv
 *
 */


#ifndef PX_COMM_MESSAGE_SETCAMERAINFOREQUEST_H
#define PX_COMM_MESSAGE_SETCAMERAINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <px_comm/CameraInfo.h>

namespace px_comm
{
template <class ContainerAllocator>
struct SetCameraInfoRequest_
{
  typedef SetCameraInfoRequest_<ContainerAllocator> Type;

  SetCameraInfoRequest_()
    : camera_info()  {
    }
  SetCameraInfoRequest_(const ContainerAllocator& _alloc)
    : camera_info(_alloc)  {
    }



   typedef  ::px_comm::CameraInfo_<ContainerAllocator>  _camera_info_type;
  _camera_info_type camera_info;




  typedef boost::shared_ptr< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCameraInfoRequest_

typedef ::px_comm::SetCameraInfoRequest_<std::allocator<void> > SetCameraInfoRequest;

typedef boost::shared_ptr< ::px_comm::SetCameraInfoRequest > SetCameraInfoRequestPtr;
typedef boost::shared_ptr< ::px_comm::SetCameraInfoRequest const> SetCameraInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px_comm::SetCameraInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'px_comm': ['/home/odroid/catkin_ws/src/px-ros-pkg/px_comm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a9e1a5d43e759a7ba44f5a4ddd63496";
  }

  static const char* value(const ::px_comm::SetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a9e1a5d43e759a7ULL;
  static const uint64_t static_value2 = 0xba44f5a4ddd63496ULL;
};

template<class ContainerAllocator>
struct DataType< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px_comm/SetCameraInfoRequest";
  }

  static const char* value(const ::px_comm::SetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
CameraInfo camera_info\n\
\n\
================================================================================\n\
MSG: px_comm/CameraInfo\n\
#######################################################################\n\
#                     Image acquisition info                          #\n\
#######################################################################\n\
\n\
# Time of image acquisition, camera coordinate frame ID\n\
Header header    # Header timestamp should be acquisition time of image\n\
                 # Header frame_id should be optical frame of camera\n\
                 # origin of frame should be optical center of camera\n\
                 # +x should point to the right in the image\n\
                 # +y should point down in the image\n\
                 # +z should point into the plane of the image\n\
\n\
\n\
#######################################################################\n\
#                      Calibration Parameters                         #\n\
#######################################################################\n\
# These are fixed during camera calibration. Their values will be the #\n\
# same in all messages until the camera is recalibrated. Note that    #\n\
# self-calibrating systems may \"recalibrate\" frequently.              #\n\
#######################################################################\n\
\n\
# The camera model used.\n\
string camera_model\n\
\n\
# The name of the camera.\n\
string camera_name\n\
\n\
# The type of the camera.\n\
string camera_type\n\
\n\
# The image dimensions with which the camera was calibrated. Normally\n\
# this will be the full camera resolution in pixels.\n\
uint32 image_width\n\
uint32 image_height\n\
\n\
# The distortion parameters, size depending on the distortion model.\n\
float64[] D\n\
\n\
# The projection parameters, size depending on the projection model.\n\
float64[] P\n\
\n\
# Other parameters which are not defined by either the distortion or\n\
# projection model.\n\
float64[] M\n\
\n\
# Pose of camera with respect to a specific reference frame.\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::px_comm::SetCameraInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetCameraInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px_comm::SetCameraInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px_comm::SetCameraInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera_info: ";
    s << std::endl;
    Printer< ::px_comm::CameraInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX_COMM_MESSAGE_SETCAMERAINFOREQUEST_H
