/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/Attitude.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_ATTITUDE_H
#define CASY_ROVER_MESSAGE_ATTITUDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace casy_rover
{
template <class ContainerAllocator>
struct Attitude_
{
  typedef Attitude_<ContainerAllocator> Type;

  Attitude_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)  {
    }
  Attitude_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , rollspeed(0.0)
    , pitchspeed(0.0)
    , yawspeed(0.0)  {
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _rollspeed_type;
  _rollspeed_type rollspeed;

   typedef float _pitchspeed_type;
  _pitchspeed_type pitchspeed;

   typedef float _yawspeed_type;
  _yawspeed_type yawspeed;




  typedef boost::shared_ptr< ::casy_rover::Attitude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::Attitude_<ContainerAllocator> const> ConstPtr;

}; // struct Attitude_

typedef ::casy_rover::Attitude_<std::allocator<void> > Attitude;

typedef boost::shared_ptr< ::casy_rover::Attitude > AttitudePtr;
typedef boost::shared_ptr< ::casy_rover::Attitude const> AttitudeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::Attitude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::Attitude_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::Attitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::Attitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::Attitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::Attitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::Attitude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::Attitude_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::Attitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0ed90d05663fe955b3f4e85f83050df";
  }

  static const char* value(const ::casy_rover::Attitude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0ed90d05663fe95ULL;
  static const uint64_t static_value2 = 0x5b3f4e85f83050dfULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::Attitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/Attitude";
  }

  static const char* value(const ::casy_rover::Attitude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::Attitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#roll                      : Roll angle (rad) (float)     \n\
#pitch                     : Pitch angle (rad) (float) \n\
#yaw                       : Yaw angle (rad) (float)\n\
#rollspeed                 : Roll angular speed (rad/s) (float)\n\
#pitchspeed                : Pitch angular speed (rad/s) (float)\n\
#yawspeed                  : Yaw angular speed (rad/s) (float)    \n\
\n\
float32 roll\n\
float32 pitch\n\
float32 yaw \n\
float32 rollspeed \n\
float32 pitchspeed\n\
float32 yawspeed\n\
";
  }

  static const char* value(const ::casy_rover::Attitude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::Attitude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.rollspeed);
      stream.next(m.pitchspeed);
      stream.next(m.yawspeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Attitude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::Attitude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::Attitude_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "rollspeed: ";
    Printer<float>::stream(s, indent + "  ", v.rollspeed);
    s << indent << "pitchspeed: ";
    Printer<float>::stream(s, indent + "  ", v.pitchspeed);
    s << indent << "yawspeed: ";
    Printer<float>::stream(s, indent + "  ", v.yawspeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_ATTITUDE_H
