/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/ControllerOutput.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_CONTROLLEROUTPUT_H
#define CASY_ROVER_MESSAGE_CONTROLLEROUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace casy_rover
{
template <class ContainerAllocator>
struct ControllerOutput_
{
  typedef ControllerOutput_<ContainerAllocator> Type;

  ControllerOutput_()
    : nav_roll(0.0)
    , nav_pitch(0.0)
    , nav_bearing(0)
    , alt_error(0.0)
    , air_spd_error(0.0)
    , xtrack_error(0.0)  {
    }
  ControllerOutput_(const ContainerAllocator& _alloc)
    : nav_roll(0.0)
    , nav_pitch(0.0)
    , nav_bearing(0)
    , alt_error(0.0)
    , air_spd_error(0.0)
    , xtrack_error(0.0)  {
    }



   typedef float _nav_roll_type;
  _nav_roll_type nav_roll;

   typedef float _nav_pitch_type;
  _nav_pitch_type nav_pitch;

   typedef int16_t _nav_bearing_type;
  _nav_bearing_type nav_bearing;

   typedef float _alt_error_type;
  _alt_error_type alt_error;

   typedef float _air_spd_error_type;
  _air_spd_error_type air_spd_error;

   typedef float _xtrack_error_type;
  _xtrack_error_type xtrack_error;




  typedef boost::shared_ptr< ::casy_rover::ControllerOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::ControllerOutput_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerOutput_

typedef ::casy_rover::ControllerOutput_<std::allocator<void> > ControllerOutput;

typedef boost::shared_ptr< ::casy_rover::ControllerOutput > ControllerOutputPtr;
typedef boost::shared_ptr< ::casy_rover::ControllerOutput const> ControllerOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::ControllerOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::ControllerOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::ControllerOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::ControllerOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::ControllerOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::ControllerOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::ControllerOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::ControllerOutput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14e8f32f6dc13cd7db7fdae805a6677b";
  }

  static const char* value(const ::casy_rover::ControllerOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14e8f32f6dc13cd7ULL;
  static const uint64_t static_value2 = 0xdb7fdae805a6677bULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/ControllerOutput";
  }

  static const char* value(const ::casy_rover::ControllerOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::ControllerOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Based on MAVLink 1.0 Messages: NAV_CONTROLLER_OUTPUT\n\
# See common.xml in MAVLink Messages\n\
\n\
# Outputs of the ArduPilot Mega controller.\n\
\n\
# Current Desired Roll, Pitch, and Yaw in degrees\n\
float32 nav_roll\n\
float32 nav_pitch\n\
int16 nav_bearing\n\
\n\
# Current error in altitude, airspeed, and crosstrack\n\
float32 alt_error\n\
float32 air_spd_error\n\
float32 xtrack_error\n\
";
  }

  static const char* value(const ::casy_rover::ControllerOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::ControllerOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nav_roll);
      stream.next(m.nav_pitch);
      stream.next(m.nav_bearing);
      stream.next(m.alt_error);
      stream.next(m.air_spd_error);
      stream.next(m.xtrack_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ControllerOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::ControllerOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::ControllerOutput_<ContainerAllocator>& v)
  {
    s << indent << "nav_roll: ";
    Printer<float>::stream(s, indent + "  ", v.nav_roll);
    s << indent << "nav_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.nav_pitch);
    s << indent << "nav_bearing: ";
    Printer<int16_t>::stream(s, indent + "  ", v.nav_bearing);
    s << indent << "alt_error: ";
    Printer<float>::stream(s, indent + "  ", v.alt_error);
    s << indent << "air_spd_error: ";
    Printer<float>::stream(s, indent + "  ", v.air_spd_error);
    s << indent << "xtrack_error: ";
    Printer<float>::stream(s, indent + "  ", v.xtrack_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_CONTROLLEROUTPUT_H
