/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/FilteredPosition.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_FILTEREDPOSITION_H
#define CASY_ROVER_MESSAGE_FILTEREDPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace casy_rover
{
template <class ContainerAllocator>
struct FilteredPosition_
{
  typedef FilteredPosition_<ContainerAllocator> Type;

  FilteredPosition_()
    : header()
    , latitude(0)
    , longitude(0)
    , altitude(0)
    , relative_altitude(0)
    , ground_x_speed(0)
    , ground_y_speed(0)
    , ground_z_speed(0)
    , heading(0)  {
    }
  FilteredPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0)
    , longitude(0)
    , altitude(0)
    , relative_altitude(0)
    , ground_x_speed(0)
    , ground_y_speed(0)
    , ground_z_speed(0)
    , heading(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _latitude_type;
  _latitude_type latitude;

   typedef int32_t _longitude_type;
  _longitude_type longitude;

   typedef int32_t _altitude_type;
  _altitude_type altitude;

   typedef int32_t _relative_altitude_type;
  _relative_altitude_type relative_altitude;

   typedef int16_t _ground_x_speed_type;
  _ground_x_speed_type ground_x_speed;

   typedef int16_t _ground_y_speed_type;
  _ground_y_speed_type ground_y_speed;

   typedef int16_t _ground_z_speed_type;
  _ground_z_speed_type ground_z_speed;

   typedef uint16_t _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::casy_rover::FilteredPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::FilteredPosition_<ContainerAllocator> const> ConstPtr;

}; // struct FilteredPosition_

typedef ::casy_rover::FilteredPosition_<std::allocator<void> > FilteredPosition;

typedef boost::shared_ptr< ::casy_rover::FilteredPosition > FilteredPositionPtr;
typedef boost::shared_ptr< ::casy_rover::FilteredPosition const> FilteredPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::FilteredPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::FilteredPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::FilteredPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::FilteredPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::FilteredPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::FilteredPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::FilteredPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::FilteredPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::FilteredPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c085fbfb9542cd7c5704f043b5e23e5c";
  }

  static const char* value(const ::casy_rover::FilteredPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc085fbfb9542cd7cULL;
  static const uint64_t static_value2 = 0x5704f043b5e23e5cULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::FilteredPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/FilteredPosition";
  }

  static const char* value(const ::casy_rover::FilteredPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::FilteredPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Based on MAVLink 1.0 Messages: GLOBAL_POSITION_INT\n\
# See common.xml in MAVLink Messages\n\
\n\
Header header\n\
\n\
# Latitude and Longitude given in deg * 10^7\n\
int32 latitude\n\
int32 longitude\n\
\n\
# Altitude given as mm\n\
int32 altitude\n\
int32 relative_altitude\n\
\n\
# Ground Speed along X, Y, and Z expressed as m/s * 100\n\
int16 ground_x_speed\n\
int16 ground_y_speed\n\
int16 ground_z_speed\n\
\n\
# Heading in degrees * 100 (set to 65536 if false)\n\
uint16 heading\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::casy_rover::FilteredPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::FilteredPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.relative_altitude);
      stream.next(m.ground_x_speed);
      stream.next(m.ground_y_speed);
      stream.next(m.ground_z_speed);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FilteredPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::FilteredPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::FilteredPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.altitude);
    s << indent << "relative_altitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.relative_altitude);
    s << indent << "ground_x_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ground_x_speed);
    s << indent << "ground_y_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ground_y_speed);
    s << indent << "ground_z_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ground_z_speed);
    s << indent << "heading: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_FILTEREDPOSITION_H
