/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/MissionItem.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_MISSIONITEM_H
#define CASY_ROVER_MESSAGE_MISSIONITEM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace casy_rover
{
template <class ContainerAllocator>
struct MissionItem_
{
  typedef MissionItem_<ContainerAllocator> Type;

  MissionItem_()
    : header()
    , mission_num(0)
    , isCurrent(0)
    , isAutoContinue(0)
    , posAcc(0.0)
    , holdTime(0.0)
    , loiterRadius(0.0)
    , yawFrom(0.0)
    , x_lat(0.0)
    , y_long(0.0)
    , z_alt(0.0)  {
    }
  MissionItem_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mission_num(0)
    , isCurrent(0)
    , isAutoContinue(0)
    , posAcc(0.0)
    , holdTime(0.0)
    , loiterRadius(0.0)
    , yawFrom(0.0)
    , x_lat(0.0)
    , y_long(0.0)
    , z_alt(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _mission_num_type;
  _mission_num_type mission_num;

   typedef uint8_t _isCurrent_type;
  _isCurrent_type isCurrent;

   typedef uint8_t _isAutoContinue_type;
  _isAutoContinue_type isAutoContinue;

   typedef float _posAcc_type;
  _posAcc_type posAcc;

   typedef float _holdTime_type;
  _holdTime_type holdTime;

   typedef float _loiterRadius_type;
  _loiterRadius_type loiterRadius;

   typedef float _yawFrom_type;
  _yawFrom_type yawFrom;

   typedef float _x_lat_type;
  _x_lat_type x_lat;

   typedef float _y_long_type;
  _y_long_type y_long;

   typedef float _z_alt_type;
  _z_alt_type z_alt;




  typedef boost::shared_ptr< ::casy_rover::MissionItem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::MissionItem_<ContainerAllocator> const> ConstPtr;

}; // struct MissionItem_

typedef ::casy_rover::MissionItem_<std::allocator<void> > MissionItem;

typedef boost::shared_ptr< ::casy_rover::MissionItem > MissionItemPtr;
typedef boost::shared_ptr< ::casy_rover::MissionItem const> MissionItemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::MissionItem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::MissionItem_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::MissionItem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::MissionItem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::MissionItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::MissionItem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::MissionItem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::MissionItem_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::MissionItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4eec5db18601d2affa66a99457a442d";
  }

  static const char* value(const ::casy_rover::MissionItem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4eec5db18601d2aULL;
  static const uint64_t static_value2 = 0xffa66a99457a442dULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::MissionItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/MissionItem";
  }

  static const char* value(const ::casy_rover::MissionItem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::MissionItem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Based on MAVLink 1.0 Messages: MISSION_ITEM\n\
# See common.xml in MAVLink Messages\n\
\n\
# Information regarding current waypoint target\n\
\n\
Header header\n\
\n\
# Mission Item Number\n\
uint16 mission_num\n\
\n\
# Boolean to show if mission item is current\n\
uint8 isCurrent\n\
uint8 isAutoContinue\n\
\n\
# Position Accuracy in meters\n\
float32 posAcc\n\
\n\
# Hold Time in ms\n\
float32 holdTime\n\
\n\
# Radius in meters for Loiter Circle.  Positive = clockwise, negative = counter\n\
float32 loiterRadius\n\
\n\
# Desired Yaw Angle in degrees\n\
float32 yawFrom\n\
\n\
# Latitude, Longitude, and Altitude\n\
float32 x_lat\n\
float32 y_long\n\
float32 z_alt\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::casy_rover::MissionItem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::MissionItem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mission_num);
      stream.next(m.isCurrent);
      stream.next(m.isAutoContinue);
      stream.next(m.posAcc);
      stream.next(m.holdTime);
      stream.next(m.loiterRadius);
      stream.next(m.yawFrom);
      stream.next(m.x_lat);
      stream.next(m.y_long);
      stream.next(m.z_alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MissionItem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::MissionItem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::MissionItem_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mission_num: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.mission_num);
    s << indent << "isCurrent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isCurrent);
    s << indent << "isAutoContinue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isAutoContinue);
    s << indent << "posAcc: ";
    Printer<float>::stream(s, indent + "  ", v.posAcc);
    s << indent << "holdTime: ";
    Printer<float>::stream(s, indent + "  ", v.holdTime);
    s << indent << "loiterRadius: ";
    Printer<float>::stream(s, indent + "  ", v.loiterRadius);
    s << indent << "yawFrom: ";
    Printer<float>::stream(s, indent + "  ", v.yawFrom);
    s << indent << "x_lat: ";
    Printer<float>::stream(s, indent + "  ", v.x_lat);
    s << indent << "y_long: ";
    Printer<float>::stream(s, indent + "  ", v.y_long);
    s << indent << "z_alt: ";
    Printer<float>::stream(s, indent + "  ", v.z_alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_MISSIONITEM_H
