/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/Status.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_STATUS_H
#define CASY_ROVER_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace casy_rover
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : header()
    , battery_voltage(0)
    , battery_current(0)
    , battery_remaining(0)
    , sensors_enabled(0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , battery_voltage(0)
    , battery_current(0)
    , battery_remaining(0)
    , sensors_enabled(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef int16_t _battery_current_type;
  _battery_current_type battery_current;

   typedef int8_t _battery_remaining_type;
  _battery_remaining_type battery_remaining;

   typedef uint32_t _sensors_enabled_type;
  _sensors_enabled_type sensors_enabled;




  typedef boost::shared_ptr< ::casy_rover::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::casy_rover::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::casy_rover::Status > StatusPtr;
typedef boost::shared_ptr< ::casy_rover::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::Status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44bba29061029309cd51365dfdec8bae";
  }

  static const char* value(const ::casy_rover::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44bba29061029309ULL;
  static const uint64_t static_value2 = 0xcd51365dfdec8baeULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/Status";
  }

  static const char* value(const ::casy_rover::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Based on MAVLink 1.0 Messages: SYS_STATUS\n\
# See common.xml in MAVLink Messages\n\
\n\
Header header\n\
\n\
# battery voltage in mV\n\
int16 battery_voltage\n\
# battery current in 10mA increments\n\
int16 battery_current\n\
# battery remaining in percentage\n\
int8  battery_remaining\n\
\n\
uint32 sensors_enabled\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::casy_rover::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.battery_voltage);
      stream.next(m.battery_current);
      stream.next(m.battery_remaining);
      stream.next(m.sensors_enabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::Status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "battery_voltage: ";
    Printer<int16_t>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "battery_current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.battery_current);
    s << indent << "battery_remaining: ";
    Printer<int8_t>::stream(s, indent + "  ", v.battery_remaining);
    s << indent << "sensors_enabled: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sensors_enabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_STATUS_H
