/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/casy_rover/msg/VFR_HUD.msg
 *
 */


#ifndef CASY_ROVER_MESSAGE_VFR_HUD_H
#define CASY_ROVER_MESSAGE_VFR_HUD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace casy_rover
{
template <class ContainerAllocator>
struct VFR_HUD_
{
  typedef VFR_HUD_<ContainerAllocator> Type;

  VFR_HUD_()
    : airspeed(0.0)
    , groundspeed(0.0)
    , heading(0)
    , throttle(0)
    , alt(0.0)
    , climb(0.0)  {
    }
  VFR_HUD_(const ContainerAllocator& _alloc)
    : airspeed(0.0)
    , groundspeed(0.0)
    , heading(0)
    , throttle(0)
    , alt(0.0)
    , climb(0.0)  {
    }



   typedef float _airspeed_type;
  _airspeed_type airspeed;

   typedef float _groundspeed_type;
  _groundspeed_type groundspeed;

   typedef int16_t _heading_type;
  _heading_type heading;

   typedef uint16_t _throttle_type;
  _throttle_type throttle;

   typedef float _alt_type;
  _alt_type alt;

   typedef float _climb_type;
  _climb_type climb;




  typedef boost::shared_ptr< ::casy_rover::VFR_HUD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::casy_rover::VFR_HUD_<ContainerAllocator> const> ConstPtr;

}; // struct VFR_HUD_

typedef ::casy_rover::VFR_HUD_<std::allocator<void> > VFR_HUD;

typedef boost::shared_ptr< ::casy_rover::VFR_HUD > VFR_HUDPtr;
typedef boost::shared_ptr< ::casy_rover::VFR_HUD const> VFR_HUDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::casy_rover::VFR_HUD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::casy_rover::VFR_HUD_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace casy_rover

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'casy_rover': ['/home/odroid/catkin_ws/src/casy_rover/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::VFR_HUD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::casy_rover::VFR_HUD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::VFR_HUD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::casy_rover::VFR_HUD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::VFR_HUD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::casy_rover::VFR_HUD_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::casy_rover::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d675e2b95b45d51cd67453c819986216";
  }

  static const char* value(const ::casy_rover::VFR_HUD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd675e2b95b45d51cULL;
  static const uint64_t static_value2 = 0xd67453c819986216ULL;
};

template<class ContainerAllocator>
struct DataType< ::casy_rover::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "casy_rover/VFR_HUD";
  }

  static const char* value(const ::casy_rover::VFR_HUD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::casy_rover::VFR_HUD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Metrics typically displayed on a HUD for fixed wing aircraft        \n\
#airspeed                  : Current airspeed in m/s (float)\n\
#groundspeed               : Current ground speed in m/s (float)\n\
#heading                   : Current heading in degrees, in compass units (0..360, 0=north) (int16_t)  \n\
#throttle                  : Current throttle setting in integer percent, 0 to 100 (uint16_t)  \n\
#alt                       : Current altitude (MSL), in meters (float)\n\
#climb                     : Current climb rate in meters/second (float)             \n\
\n\
float32 airspeed \n\
float32 groundspeed \n\
int16 heading\n\
uint16 throttle\n\
float32 alt \n\
float32 climb\n\
";
  }

  static const char* value(const ::casy_rover::VFR_HUD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::casy_rover::VFR_HUD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.airspeed);
      stream.next(m.groundspeed);
      stream.next(m.heading);
      stream.next(m.throttle);
      stream.next(m.alt);
      stream.next(m.climb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct VFR_HUD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::casy_rover::VFR_HUD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::casy_rover::VFR_HUD_<ContainerAllocator>& v)
  {
    s << indent << "airspeed: ";
    Printer<float>::stream(s, indent + "  ", v.airspeed);
    s << indent << "groundspeed: ";
    Printer<float>::stream(s, indent + "  ", v.groundspeed);
    s << indent << "heading: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heading);
    s << indent << "throttle: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.throttle);
    s << indent << "alt: ";
    Printer<float>::stream(s, indent + "  ", v.alt);
    s << indent << "climb: ";
    Printer<float>::stream(s, indent + "  ", v.climb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASY_ROVER_MESSAGE_VFR_HUD_H
