"""autogenerated by genpy from casy_rover/FilteredPosition.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class FilteredPosition(genpy.Message):
  _md5sum = "c085fbfb9542cd7c5704f043b5e23e5c"
  _type = "casy_rover/FilteredPosition"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# Based on MAVLink 1.0 Messages: GLOBAL_POSITION_INT
# See common.xml in MAVLink Messages

Header header

# Latitude and Longitude given in deg * 10^7
int32 latitude
int32 longitude

# Altitude given as mm
int32 altitude
int32 relative_altitude

# Ground Speed along X, Y, and Z expressed as m/s * 100
int16 ground_x_speed
int16 ground_y_speed
int16 ground_z_speed

# Heading in degrees * 100 (set to 65536 if false)
uint16 heading

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','latitude','longitude','altitude','relative_altitude','ground_x_speed','ground_y_speed','ground_z_speed','heading']
  _slot_types = ['std_msgs/Header','int32','int32','int32','int32','int16','int16','int16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,latitude,longitude,altitude,relative_altitude,ground_x_speed,ground_y_speed,ground_z_speed,heading

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FilteredPosition, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latitude is None:
        self.latitude = 0
      if self.longitude is None:
        self.longitude = 0
      if self.altitude is None:
        self.altitude = 0
      if self.relative_altitude is None:
        self.relative_altitude = 0
      if self.ground_x_speed is None:
        self.ground_x_speed = 0
      if self.ground_y_speed is None:
        self.ground_y_speed = 0
      if self.ground_z_speed is None:
        self.ground_z_speed = 0
      if self.heading is None:
        self.heading = 0
    else:
      self.header = std_msgs.msg.Header()
      self.latitude = 0
      self.longitude = 0
      self.altitude = 0
      self.relative_altitude = 0
      self.ground_x_speed = 0
      self.ground_y_speed = 0
      self.ground_z_speed = 0
      self.heading = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4i3hH.pack(_x.latitude, _x.longitude, _x.altitude, _x.relative_altitude, _x.ground_x_speed, _x.ground_y_speed, _x.ground_z_speed, _x.heading))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.latitude, _x.longitude, _x.altitude, _x.relative_altitude, _x.ground_x_speed, _x.ground_y_speed, _x.ground_z_speed, _x.heading,) = _struct_4i3hH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_4i3hH.pack(_x.latitude, _x.longitude, _x.altitude, _x.relative_altitude, _x.ground_x_speed, _x.ground_y_speed, _x.ground_z_speed, _x.heading))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.latitude, _x.longitude, _x.altitude, _x.relative_altitude, _x.ground_x_speed, _x.ground_y_speed, _x.ground_z_speed, _x.heading,) = _struct_4i3hH.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i3hH = struct.Struct("<4i3hH")
_struct_3I = struct.Struct("<3I")
