"""autogenerated by genpy from casy_rover/Waypoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Waypoint(genpy.Message):
  _md5sum = "6dac49f8cf4308a151d9b97deaca8a40"
  _type = "casy_rover/Waypoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# latitude and longitude given in decimal degrees (* 10^7)
int32 latitude
int32 longitude

# height in mm
int32 altitude

# posAcc given in mm
uint16 pos_acc

# max speed to travel to waypoint in % of 100
uint8 speed_to

# time to stay at waypoint in ms
uint16 hold_time

# yawFrom angle given in degrees (* 1000)
int32 yaw_from

# camera pan and tilt angles during waypoint travel given in degrees (* 1000)
int32 pan_angle
int32 tilt_angle

# Type of Waypoint
uint8 waypoint_type

uint8 TYPE_NAV = 1
uint8 TYPE_CONDITION_YAW = 2
uint8 TYPE_CONDITION_CHANGE_ALT = 3
uint8 TYPE_TAKEOFF = 4

"""
  # Pseudo-constants
  TYPE_NAV = 1
  TYPE_CONDITION_YAW = 2
  TYPE_CONDITION_CHANGE_ALT = 3
  TYPE_TAKEOFF = 4

  __slots__ = ['latitude','longitude','altitude','pos_acc','speed_to','hold_time','yaw_from','pan_angle','tilt_angle','waypoint_type']
  _slot_types = ['int32','int32','int32','uint16','uint8','uint16','int32','int32','int32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,altitude,pos_acc,speed_to,hold_time,yaw_from,pan_angle,tilt_angle,waypoint_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Waypoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0
      if self.longitude is None:
        self.longitude = 0
      if self.altitude is None:
        self.altitude = 0
      if self.pos_acc is None:
        self.pos_acc = 0
      if self.speed_to is None:
        self.speed_to = 0
      if self.hold_time is None:
        self.hold_time = 0
      if self.yaw_from is None:
        self.yaw_from = 0
      if self.pan_angle is None:
        self.pan_angle = 0
      if self.tilt_angle is None:
        self.tilt_angle = 0
      if self.waypoint_type is None:
        self.waypoint_type = 0
    else:
      self.latitude = 0
      self.longitude = 0
      self.altitude = 0
      self.pos_acc = 0
      self.speed_to = 0
      self.hold_time = 0
      self.yaw_from = 0
      self.pan_angle = 0
      self.tilt_angle = 0
      self.waypoint_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3iHBH3iB.pack(_x.latitude, _x.longitude, _x.altitude, _x.pos_acc, _x.speed_to, _x.hold_time, _x.yaw_from, _x.pan_angle, _x.tilt_angle, _x.waypoint_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.latitude, _x.longitude, _x.altitude, _x.pos_acc, _x.speed_to, _x.hold_time, _x.yaw_from, _x.pan_angle, _x.tilt_angle, _x.waypoint_type,) = _struct_3iHBH3iB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3iHBH3iB.pack(_x.latitude, _x.longitude, _x.altitude, _x.pos_acc, _x.speed_to, _x.hold_time, _x.yaw_from, _x.pan_angle, _x.tilt_angle, _x.waypoint_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 30
      (_x.latitude, _x.longitude, _x.altitude, _x.pos_acc, _x.speed_to, _x.hold_time, _x.yaw_from, _x.pan_angle, _x.tilt_angle, _x.waypoint_type,) = _struct_3iHBH3iB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3iHBH3iB = struct.Struct("<3iHBH3iB")
