/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/catkin_ws/src/px-ros-pkg/px_comm/msg/OpticalFlow.msg
 *
 */


#ifndef PX_COMM_MESSAGE_OPTICALFLOW_H
#define PX_COMM_MESSAGE_OPTICALFLOW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace px_comm
{
template <class ContainerAllocator>
struct OpticalFlow_
{
  typedef OpticalFlow_<ContainerAllocator> Type;

  OpticalFlow_()
    : header()
    , ground_distance(0.0)
    , flow_x(0)
    , flow_y(0)
    , velocity_x(0.0)
    , velocity_y(0.0)
    , quality(0)  {
    }
  OpticalFlow_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ground_distance(0.0)
    , flow_x(0)
    , flow_y(0)
    , velocity_x(0.0)
    , velocity_y(0.0)
    , quality(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _ground_distance_type;
  _ground_distance_type ground_distance;

   typedef int16_t _flow_x_type;
  _flow_x_type flow_x;

   typedef int16_t _flow_y_type;
  _flow_y_type flow_y;

   typedef float _velocity_x_type;
  _velocity_x_type velocity_x;

   typedef float _velocity_y_type;
  _velocity_y_type velocity_y;

   typedef uint8_t _quality_type;
  _quality_type quality;




  typedef boost::shared_ptr< ::px_comm::OpticalFlow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px_comm::OpticalFlow_<ContainerAllocator> const> ConstPtr;

}; // struct OpticalFlow_

typedef ::px_comm::OpticalFlow_<std::allocator<void> > OpticalFlow;

typedef boost::shared_ptr< ::px_comm::OpticalFlow > OpticalFlowPtr;
typedef boost::shared_ptr< ::px_comm::OpticalFlow const> OpticalFlowConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px_comm::OpticalFlow_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px_comm::OpticalFlow_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace px_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'px_comm': ['/home/odroid/catkin_ws/src/px-ros-pkg/px_comm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::px_comm::OpticalFlow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_comm::OpticalFlow_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_comm::OpticalFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_comm::OpticalFlow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_comm::OpticalFlow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_comm::OpticalFlow_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px_comm::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6705fe0e94fea14978a508d00cf97427";
  }

  static const char* value(const ::px_comm::OpticalFlow_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6705fe0e94fea149ULL;
  static const uint64_t static_value2 = 0x78a508d00cf97427ULL;
};

template<class ContainerAllocator>
struct DataType< ::px_comm::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px_comm/OpticalFlow";
  }

  static const char* value(const ::px_comm::OpticalFlow_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px_comm::OpticalFlow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 ground_distance  # distance to ground in meters\n\
int16   flow_x           # x-component of optical flow in pixels\n\
int16   flow_y           # y-component of optical flow in pixels\n\
float32 velocity_x       # x-component of scaled optical flow in m/s\n\
float32 velocity_y       # y-component of scaled optical flow in m/s\n\
uint8   quality          # quality of optical flow estimate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::px_comm::OpticalFlow_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px_comm::OpticalFlow_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ground_distance);
      stream.next(m.flow_x);
      stream.next(m.flow_y);
      stream.next(m.velocity_x);
      stream.next(m.velocity_y);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct OpticalFlow_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px_comm::OpticalFlow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px_comm::OpticalFlow_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ground_distance: ";
    Printer<float>::stream(s, indent + "  ", v.ground_distance);
    s << indent << "flow_x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flow_x);
    s << indent << "flow_y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.flow_y);
    s << indent << "velocity_x: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_x);
    s << indent << "velocity_y: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_y);
    s << indent << "quality: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX_COMM_MESSAGE_OPTICALFLOW_H
