/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/odroid/catkin_ws/src/px-ros-pkg/px_comm/srv/SetCameraInfo.srv
 *
 */


#ifndef PX_COMM_MESSAGE_SETCAMERAINFO_H
#define PX_COMM_MESSAGE_SETCAMERAINFO_H

#include <ros/service_traits.h>


#include <px_comm/SetCameraInfoRequest.h>
#include <px_comm/SetCameraInfoResponse.h>


namespace px_comm
{

struct SetCameraInfo
{

typedef SetCameraInfoRequest Request;
typedef SetCameraInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCameraInfo
} // namespace px_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::px_comm::SetCameraInfo > {
  static const char* value()
  {
    return "b7b33d05bd0d56b83943d2370771da4c";
  }

  static const char* value(const ::px_comm::SetCameraInfo&) { return value(); }
};

template<>
struct DataType< ::px_comm::SetCameraInfo > {
  static const char* value()
  {
    return "px_comm/SetCameraInfo";
  }

  static const char* value(const ::px_comm::SetCameraInfo&) { return value(); }
};


// service_traits::MD5Sum< ::px_comm::SetCameraInfoRequest> should match 
// service_traits::MD5Sum< ::px_comm::SetCameraInfo > 
template<>
struct MD5Sum< ::px_comm::SetCameraInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::px_comm::SetCameraInfo >::value();
  }
  static const char* value(const ::px_comm::SetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::px_comm::SetCameraInfoRequest> should match 
// service_traits::DataType< ::px_comm::SetCameraInfo > 
template<>
struct DataType< ::px_comm::SetCameraInfoRequest>
{
  static const char* value()
  {
    return DataType< ::px_comm::SetCameraInfo >::value();
  }
  static const char* value(const ::px_comm::SetCameraInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::px_comm::SetCameraInfoResponse> should match 
// service_traits::MD5Sum< ::px_comm::SetCameraInfo > 
template<>
struct MD5Sum< ::px_comm::SetCameraInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::px_comm::SetCameraInfo >::value();
  }
  static const char* value(const ::px_comm::SetCameraInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::px_comm::SetCameraInfoResponse> should match 
// service_traits::DataType< ::px_comm::SetCameraInfo > 
template<>
struct DataType< ::px_comm::SetCameraInfoResponse>
{
  static const char* value()
  {
    return DataType< ::px_comm::SetCameraInfo >::value();
  }
  static const char* value(const ::px_comm::SetCameraInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PX_COMM_MESSAGE_SETCAMERAINFO_H
