#!/bin/bash
source /opt/ros/indigo/setup.bash
source /home/odroid/catkin_ws/devel/setup.bash
export ROS_WORKSPACE=/home/odroid/catkin_ws
export DISPLAY=:0
kill $(pgrep inotifywait)
rosnode kill camera_handler_SHERPA
rosnode kill guidance_node_amsl
rosnode kill mavros
rosnode kill mms
rosnode kill usb_cam
rosnode kill web_video_server
rosnode kill rosout
